services:

  php-fpm:
    build:
      context: ./containers/php-fpm
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    volumes:
      - ../back:/var/www/back
      - ./containers/php-fpm/logs/commandhistory:/commandhistory
    user: "root:root"
    command: php-fpm
    working_dir: /var/www/back
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.34
    volumes:
      - ./containers/mysql/databases:/var/lib/mysql
    ports:
      - "${MYSQL_FORWARD_PORT:-33061}:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
